### ISSUE TITLE
Https links not working

### ISSUE THREAD

**Issue by michelesbw** [pluginlotto/izap-videos#11]
Hi,
upgraded to elgg 1.8.16 and latest iZap bridge 2.1.5 and videos 4.2.1b both from github.
Activated ok but I still see the https youtube issue "Error saving thumb, unable to write the file on server" any solution?

Those https videos from youtube can not be added at all and the problem is that if you add alternate http link from youtube on a https site like mine, all browsers block the visualization because of the 'mixed' content on the page and users simply think the site has something wrong...

Cheers

**Comment by monika-izap** [comment]
@michelesbw This issue has been resolved in latest version of iZAP-Videos Plugin. You can download it from https://github.com/pluginlotto/izap-videos or https://community.elgg.org/plugins/384975#
